services:
  mysql-db:
    image: mysql:8.0
    container_name: bd_matricula
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=matriculadb
      - TZ=America/Lima
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin123"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  mysql_data:
